apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-api-ingress
  namespace: metrics-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: metrics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metrics-api
                port:
                  number: 8080
